# Generated by Django 5.2.17 on 2026-08-23 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('telegram_contact', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True, help_text='Owner uchun ichki izoh')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('label', models.CharField(blank=True, help_text='Owner uchun eslatma, masalan mijoz ismi/tashkiloti', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes', to='payments.company')),
            ],
        ),
        migrations.CreateModel(
            name='CodeVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_attempted', models.CharField(max_length=6)),
                ('ip_address', models.GenericIPAddressField()),
                ('was_successful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.customercode')),
            ],
            options={
                'verbose_name': 'Kod tekshirish logi',
                'verbose_name_plural': 'Kod tekshirish loglari',
            },
        ),
        migrations.CreateModel(
            name='AccessSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('customer_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.customercode')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_snapshot', models.CharField(blank=True, help_text="To'lov paytida kod biriktirilgan kompaniya nomi. Bo'sh = kompaniyasiz to'lov.", max_length=255)),
                ('customer_code_snapshot', models.CharField(max_length=6)),
                ('amount', models.PositiveBigIntegerField(help_text='Minor birlikda (tiyin)')),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'landi"), ('failed', 'Muvaffaqiyatsiz'), ('expired', "Muddati o'tdi"), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20)),
                ('gateway_invoice_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=128, null=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('gateway_raw_response', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, help_text='Referens uchun. Hisobotlarda company_name_snapshot ishlatilsin!', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.company')),
                ('customer_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.customercode')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.accesssession')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
            },
        ),
        migrations.AddIndex(
            model_name='customercode',
            index=models.Index(fields=['code'], name='payments_cu_code_1c8dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='codeverificationlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='payments_co_ip_addr_77cf00_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_invoice_id'], name='payments_pa_gateway_450cf3_idx'),
        ),
    ]
