# Generated by Django 5.2.17 on 2026-08-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('event', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook logi',
                'verbose_name_plural': 'Webhook loglari',
            },
        ),
    ]
