# Generated by Django 5.2.17 on 2026-08-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_test',
            field=models.BooleanField(default=False, help_text="To'lov yaratilgan paytdagi MONTRA_MODE=TEST bo'lsa True. Snapshot maydon — keyinchalik o'zgartirilmaydi (Telegram xabarnomasida 'test' belgisi shu asosda ko'rsatiladi)."),
        ),
    ]
