# Generated by Django 5.1.4 on 2026-08-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_is_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='session',
        ),
        migrations.RemoveField(
            model_name='codeverificationlog',
            name='matched_code',
        ),
        migrations.RemoveField(
            model_name='customercode',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer_code',
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer_code_snapshot',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.DeleteModel(
            name='AccessSession',
        ),
        migrations.DeleteModel(
            name='CodeVerificationLog',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CustomerCode',
        ),
    ]
