"""
Django settings for arion_export project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-1r@jmv)_^_e6ax0k%be(i-vk-7o_0seu0!8)(aj91y&x+x^pu@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'django_ratelimit',
    'import_export',
    'django_celery_results',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CommonMiddleware'dan OLDIN bo'lishi shart
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS — frontend (arion-export.uz) alohida domenda, shuning uchun bu
# sozlama bo'lmasa brauzer cross-origin so'rovlarni bloklaydi.
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS', 'https://arion-export.uz'
).split(',')

ROOT_URLCONF = 'arion_export.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'arion_export.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite for development if PostgreSQL is not configured
if os.getenv('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'arion_export'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
}


# DRF Spectacular (OpenAPI)
SPECTACULAR_SETTINGS = {
    'TITLE': 'ARION Export Payment API',
    'DESCRIPTION': 'Kod-asosli to\'lov tizimi uchun API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE


# Redis Cache (for rate limiting)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://localhost:6379/1'),
    }
}


# MONTRA Payment Gateway Configuration
MONTRA_MODE = os.getenv('MONTRA_MODE', 'TEST')

if MONTRA_MODE == 'LIVE':
    MONTRA_API_KEY = os.getenv('MONTRA_API_KEY_LIVE')
    MONTRA_SECRET_KEY = os.getenv('MONTRA_SECRET_KEY_LIVE')
    MONTRA_BASE_URL = os.getenv('MONTRA_BASE_URL_LIVE', 'https://api.montratech.com/api/v1')
    MONTRA_WEBHOOK_SECRET = os.getenv('MONTRA_WEBHOOK_SECRET_LIVE')
else:
    MONTRA_API_KEY = os.getenv('MONTRA_API_KEY_TEST')
    MONTRA_SECRET_KEY = os.getenv('MONTRA_SECRET_KEY_TEST')
    MONTRA_BASE_URL = os.getenv('MONTRA_BASE_URL_TEST', 'https://api.montratech.com/api/v1')
    MONTRA_WEBHOOK_SECRET = os.getenv('MONTRA_WEBHOOK_SECRET_TEST')

# MUHIM: MONTRA_WEBHOOK_SECRET — Dashboard → Settings → Webhooks'dagi
# alohida "Webhook Secret". Bu MONTRA_SECRET_KEY (API so'rovlarini
# imzolash uchun) BILAN BOG'LIQ EMAS — ikkalasini aralashtirmang.
# https://docs.montratech.com/ru/webhooks/signature

# Nginx orqasida deploy qilinganda, `X-Forwarded-For` headeri faqat shu
# ro'yxatdagi IP'lardan (ya'ni Nginx'ning o'zidan) kelgan so'rovlarda
# ishonchli hisoblanadi — aks holda mijoz uni o'zi soxtalashtirib,
# IP-based rate-limitni chetlab o'tishi mumkin edi.
# Production'da Nginx odatda 127.0.0.1 dan proxy_pass qiladi.
TRUSTED_PROXY_IPS = os.getenv('TRUSTED_PROXY_IPS', '127.0.0.1').split(',')


# Telegram Configuration
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')


# Sentry Configuration
SENTRY_DSN = os.getenv('SENTRY_DSN')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
        ],
        traces_sample_rate=0.1,
        profiles_sample_rate=0.1,
    )


# Jazzmin Admin Theme Configuration
JAZZMIN_SETTINGS = {
    # title
    "site_title": "ARION Export",
    # header
    "site_header": "ARION Export",
    # brand name
    "site_brand": "ARION Export",
    # logo
    "site_logo": "img/logo.png",
    # logo icon
    "site_logo_icon": "img/logo-icon.png",
    # copyright
    "copyright": "ARION Export © 2024",
    # welcome sign
    "welcome_sign": "Xush kelibsiz",
    # navigation
    "navigation": [
        {"app": "payments", "models": ["company"], "label": "Kompaniyalar"},
        {"app": "payments", "models": ["customercode"], "label": "Kodlar"},
        {"app": "payments", "models": ["payment"], "label": "To'lovlar"},
        {"app": "payments", "models": ["accesssession"], "label": "Sessiyalar"},
        {"app": "payments", "models": ["codeverificationlog"], "label": "Loglar"},
    ],
    # links
    "links": [
        {"model": "payment", "label": "To'lovlar", "url": "/admin/payments/payment/"},
        {"model": "customercode", "label": "Kod qo'shish", "url": "/admin/payments/customercode/add/"},
    ],
    # user menu
    "usermenu": [
        {"title": "Profil", "url": "#"},
        {"title": "Chiqish", "url": "admin:logout"},
    ],
    # top menu
    "top_menu": [
        {"title": "Dashboard", "url": "/admin/"},
        {"title": "API Docs", "url": "/api/docs/", "external": True},
    ],
    # hide apps
    "hide_apps": [],
    # hide models
    "hide_models": [],
    # icons
    "icons": {
        "company": "fas fa-building",
        "customercode": "fas fa-key",
        "payment": "fas fa-credit-card",
        "accesssession": "fas fa-clock",
        "codeverificationlog": "fas fa-history",
    },
    # languages
    "language_chooser": True,
    # show ui builder
    "show_ui_builder": False,
    # date format
    "date_format": "DD.MM.YYYY",
    # time format
    "time_format": "HH:mm:ss",
    # datetime format
    "datetime_format": "DD.MM.YYYY HH:mm:ss",
    # decimal separator
    "decimal_separator": ",",
    # thousand separator
    "thousand_separator": " ",
    # x frame options
    "x_frame_options": "SAMEORIGIN",
    # default theme
    "default_theme": "light",
    # themes
    "themes": {
        "light": {
            "primary": "#4361ee",
            "secondary": "#3f37c9",
            "accent": "#4895ef",
            "success": "#4cc9f0",
            "info": "#4cc9f0",
            "warning": "#f72585",
            "danger": "#7209b7",
            "light": "#f8f9fa",
            "dark": "#343a40",
        },
        "dark": {
            "primary": "#4361ee",
            "secondary": "#3f37c9",
            "accent": "#4895ef",
            "success": "#4cc9f0",
            "info": "#4cc9f0",
            "warning": "#f72585",
            "danger": "#7209b7",
            "light": "#f8f9fa",
            "dark": "#343a40",
        },
    },
}


# Language configuration
LANGUAGE_CODE = 'uz'

LANGUAGES = [
    ('uz', 'O\'zbek'),
    ('ru', 'Русский'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

USE_I18N = True
USE_L10N = True

